import { DM_Sans, Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { SmoothScroll } from './v2/components/smooth-scroll';
const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});
const dmSans = DM_Sans({
    variable: '--font-dm-sans',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});

const nyghtSerif = localFont({
    variable: '--font-nyght-serif',
    src: [
        {
            path: './fonts/NyghtSerif-Regular.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: './fonts/NyghtSerif-RegularItalic.woff2',
            weight: '400',
            style: 'italic',
        },
    ],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body
                suppressHydrationWarning
                className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} ${nyghtSerif.variable} antialiased`}>
                {children}
                <SmoothScroll />
            </body>
        </html>
    );
}

